config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  resources :quotes

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true,
                      length: { minimum: 5 }
end

app/models/quote.rb
class Quote < ActiveRecord::Base
    validates :content, presence: true
    validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def index
        @quote = Quote.all
    end

    def show
        @quote = Quote.find(params[:id])
    end

    def new
        @quote = Quote.new
    end

    def edit
        @quote = Quote.find(params[:id])
    end

    def create
        @quote = Quote.new(quote_params)

        if @quote.save
            redirect_to @quote
        else
            render 'new'
        end
    end

    def update
      @quote = Quote.find(params[:id])

      if @quote.update(quote_params)
        redirect_to @quote
      else
        render 'edit'
      end
    end

    def destroy
        @quote = Quote.find(params[:id])
        @quote.destroy

        redirect_to quotes_path
    end

    private
        def quote_params
            params.require(:quote).permit(:content, :author)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote do |f| %>

  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quote.errors.count, "error") %> prohibited
        this quote from being saved:
      </h2>
      <ul>
        <% @quote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<%= link_to 'New quote', new_quote_path %>

<table>
  <tr>
    <th>Quote</th>
    <th>Author</th>
    <th colspan="3"></th>
  </tr>

  <% @quote.each do |quote| %>
    <tr>
      <td><%= quote.content %></td>
      <td><%= quote.author %></td>
      <td><%= link_to 'Show', quote_path(quote) %></td>
      <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
      <td><%= link_to 'Destroy', quote_path(quote),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/quotes/show.html.erb
<p>
  <strong>Quote:</strong>
  <%= @quote.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/welcome/index.html.erb
<h1>Welcome to the blog!</h1>

<%= link_to 'Articles', articles_path %>
<%= link_to 'Quotes', quotes_path %>